name: options_file
version: 0.10.0
author: James Ots <code@jamesots.com>
description: Read options files
homepage: https://github.com/jamesots/optionsfile
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
