name: options_file
version: 0.9.14
author: James Ots <code@jamesots.com>
description: Read options files
homepage: https://github.com/jamesots/optionsfile
environment:
  sdk: '>=0.6.13'
dependencies:
  unittest: '>=0.6.13'
