name: options_file
version: 0.10.0
author: James Ots <code@jamesots.com>
description: Read options files
homepage: https://github.com/jamesots/optionsfile
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  unittest: '>=0.12.0'
